name: BDD Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    services:
      couchdb:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb                
        options: >-
          --health-cmd "curl -X GET http://postgres:5432/"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl wget python3-selenium

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run the server locally
        run: |
          echo "\n*** CREATING TEST DB ***\n"
          curl -X PUT postgresql://postgres:postgres@postgres:5432/testdb
          echo "\n*** STARTING APPLICATION ***\n"
          gunicorn --log-level=critical --bind=0.0.0.0:8080 service:app &
          sleep 5
          curl -I http://localhost:8080/
          echo "\n*** SERVER IS RUNNING ***"
        env:
          DATABASE_URI: "postgresql://postgres:postgres@postgres:5432/testdb"

      - name: Run unit tests with behave
        run: behave
  